# Generated by Django 5.1.7 on 2025-03-12 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_specialty_doctor_speacialty_delete_specialties'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='speacialty',
            new_name='specialties',
        ),
    ]
